import { test, expect } from '@playwright/test';
import { TICK_RATE } from '../shared/flight';
import { MAX_HEALTH } from '../shared/lifecycle';
import type { FlightConnection } from '../src/network';
type DebugWindow = Window & { __HORIZON_FLIGHT__: FlightConnection };
test('compact HUD, F3 controls, actual RTT/metrics and room-scoped roster updates work', async ({ page, context }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('/'); await page.locator('#server-url').fill('http://127.0.0.1:3002');
  await page.locator('#create').click();
  await expect(page.locator('#hud-health-value')).toHaveText(`${MAX_HEALTH} / ${MAX_HEALTH}`);
  await expect(page.locator('#hud-health-bar')).toHaveJSProperty('value', MAX_HEALTH);
  await expect(page.locator('#hud-health-bar')).toHaveJSProperty('max', MAX_HEALTH);
  for (const [id, text] of [['shield', 'SHIELD 50 / 50'], ['ammo', 'AMMO 12 / 12']]) await expect(page.locator(`#hud-${id}`)).toHaveText(text);
  await expect(page.locator('#hud-weapon')).toHaveCount(0);
  await expect(page.locator('#debug-overlay')).toBeHidden();
  await page.keyboard.press('F3'); await expect(page.locator('#debug-overlay')).toBeVisible();
  await page.evaluate(() => window.dispatchEvent(new KeyboardEvent('keydown', { code: 'F3', repeat: true })));
  await expect(page.locator('#debug-overlay')).toBeVisible();
  await expect(page.locator('#debug-players')).toHaveText('Players: 1');
  // Observe the real, existing RTT callback; never substitute a fake ping value.
  const measured = await page.evaluate(() => new Promise<number>(resolve => {
    const c = (window as unknown as DebugWindow).__HORIZON_FLIGHT__ as unknown as {
      callbacks: { ping: (ms: number | null) => void }; measurePing: () => void;
    };
    const original = c.callbacks.ping;
    c.callbacks.ping = ms => { original(ms); if (ms !== null) { c.callbacks.ping = original; resolve(ms); } };
    c.measurePing();
  }));
  await expect(page.locator('#ping')).toHaveText(`Ping: ${measured} ms`);
  await expect(page.locator('#debug-fps')).toHaveText(/FPS: \d+/);
  await expect(page.locator('#debug-server')).toHaveText(new RegExp(`Server: ${TICK_RATE} Hz \\(recv \\d+\\.\\d/s\\)`));
  await expect.poll(async () => Number((await page.locator('#debug-server').textContent())?.match(/recv ([\d.]+)/)?.[1] ?? 0)).toBeGreaterThan(0);
  const before = await page.evaluate(() => (window as unknown as DebugWindow).__HORIZON_FLIGHT__.latest!.players[0].x);
  await page.keyboard.down('d'); await page.keyboard.press('F3');
  await expect(page.locator('#debug-overlay')).toBeHidden();
  await expect.poll(() => page.evaluate(() => (window as unknown as DebugWindow).__HORIZON_FLIGHT__.latest!.players[0].x)).toBeGreaterThan(before);
  await page.keyboard.up('d'); await page.keyboard.press('r');
  await expect(page.locator('#hud-reload')).toHaveText(''); // R on a full magazine is a no-op, not a flight reset.
  expect(await page.evaluate(() => (window as unknown as DebugWindow).__HORIZON_FLIGHT__.latest!.players[0].x)).toBeGreaterThan(before);
  await page.keyboard.press('F3');
  const code = (await page.locator('#room-code-display').textContent())!;
  const peer = await context.newPage(); await peer.goto('/'); await peer.locator('#server-url').fill('http://127.0.0.1:3002');
  await peer.locator('#room-code').fill(code); await peer.locator('#join').click();
  await expect(page.locator('#debug-players')).toHaveText('Players: 2');
  const isolated = await context.newPage(); await isolated.goto('/'); await isolated.locator('#server-url').fill('http://127.0.0.1:3002'); await isolated.locator('#create').click();
  await expect(isolated.locator('#debug-players')).toHaveText('Players: 1');
  await expect(page.locator('#debug-players')).toHaveText('Players: 2');
  await page.screenshot({ path: 'test-results/step7-hud.png', fullPage: true });
  await page.setViewportSize({ width: 680, height: 960 });
  const hudBox = await page.locator('.gameplay-hud').boundingBox();
  const debugBox = await page.locator('#debug-overlay').boundingBox();
  const gameBox = await page.locator('#game').boundingBox();
  expect(hudBox && debugBox && gameBox).toBeTruthy();
  expect(hudBox!.y).toBeGreaterThan(gameBox!.y + 90);
  expect(hudBox!.x + hudBox!.width).toBeLessThanOrEqual(gameBox!.x + gameBox!.width);
  expect(hudBox!.y + hudBox!.height).toBeLessThanOrEqual(gameBox!.y + gameBox!.height);
  expect(debugBox!.y).toBeGreaterThanOrEqual(gameBox!.y + gameBox!.height);
  await peer.close(); await expect(page.locator('#debug-players')).toHaveText('Players: 1');
  await page.evaluate(() => (window as unknown as DebugWindow).__HORIZON_FLIGHT__.socket.disconnect());
  await expect(page.locator('#ping')).toHaveText('Ping: —');
  await expect(page.locator('#debug-players')).toHaveText('Players: —');
  await expect(page.locator('#debug-server')).toHaveText(`Server: ${TICK_RATE} Hz (recv —)`);
  await isolated.close(); expect(errors).toEqual([]);
});
